// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: writestore.proto

package writestore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PasteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *PasteReq) Reset() {
	*x = PasteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_writestore_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PasteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasteReq) ProtoMessage() {}

func (x *PasteReq) ProtoReflect() protoreflect.Message {
	mi := &file_writestore_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasteReq.ProtoReflect.Descriptor instead.
func (*PasteReq) Descriptor() ([]byte, []int) {
	return file_writestore_proto_rawDescGZIP(), []int{0}
}

func (x *PasteReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type PasteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *PasteResp) Reset() {
	*x = PasteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_writestore_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PasteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasteResp) ProtoMessage() {}

func (x *PasteResp) ProtoReflect() protoreflect.Message {
	mi := &file_writestore_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasteResp.ProtoReflect.Descriptor instead.
func (*PasteResp) Descriptor() ([]byte, []int) {
	return file_writestore_proto_rawDescGZIP(), []int{1}
}

func (x *PasteResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_writestore_proto protoreflect.FileDescriptor

var file_writestore_proto_rawDesc = []byte{
	0x0a, 0x10, 0x77, 0x72, 0x69, 0x74, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x77, 0x72, 0x69, 0x74, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x22, 0x24,
	0x0a, 0x08, 0x50, 0x61, 0x73, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x22, 0x1d, 0x0a, 0x09, 0x50, 0x61, 0x73, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x6c, 0x32, 0x49, 0x0a, 0x0a, 0x57, 0x72, 0x69, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x50, 0x61, 0x73, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x14, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x50,
	0x61, 0x73, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x2e, 0x50, 0x61, 0x73, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0e,
	0x5a, 0x0c, 0x2e, 0x2f, 0x77, 0x72, 0x69, 0x74, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_writestore_proto_rawDescOnce sync.Once
	file_writestore_proto_rawDescData = file_writestore_proto_rawDesc
)

func file_writestore_proto_rawDescGZIP() []byte {
	file_writestore_proto_rawDescOnce.Do(func() {
		file_writestore_proto_rawDescData = protoimpl.X.CompressGZIP(file_writestore_proto_rawDescData)
	})
	return file_writestore_proto_rawDescData
}

var file_writestore_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_writestore_proto_goTypes = []interface{}{
	(*PasteReq)(nil),  // 0: writestore.PasteReq
	(*PasteResp)(nil), // 1: writestore.PasteResp
}
var file_writestore_proto_depIdxs = []int32{
	0, // 0: writestore.WriteStore.PasteContent:input_type -> writestore.PasteReq
	1, // 1: writestore.WriteStore.PasteContent:output_type -> writestore.PasteResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_writestore_proto_init() }
func file_writestore_proto_init() {
	if File_writestore_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_writestore_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PasteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_writestore_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PasteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_writestore_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_writestore_proto_goTypes,
		DependencyIndexes: file_writestore_proto_depIdxs,
		MessageInfos:      file_writestore_proto_msgTypes,
	}.Build()
	File_writestore_proto = out.File
	file_writestore_proto_rawDesc = nil
	file_writestore_proto_goTypes = nil
	file_writestore_proto_depIdxs = nil
}
